export const NODES_FETCH_REQUESTED = 'NODES_FETCH_REQUESTED';
export const NODES_FETCH_SUCCEEDED = 'NODES_FETCH_SUCCEEDED';
export const NODES_FETCH_FAILED = 'NODES_FETCH_FAILED';

export const BOTS_FETCH_REQUESTED = 'NODES_FETCH_REQUESTED';
export const BOTS_FETCH_SUCCEEDED = 'BOTS_FETCH_SUCCEEDED';
export const BOTS_FETCH_FAILED = 'BOTS_FETCH_FAILED';